### ISSUE TITLE
More splitting

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib-fortran#24]
As a follow-up on #9, it would be nice to split the following algorithms into separate routines, to allow more flexibility in downstream libraries like [fastscape](https://github.com/fastscape-lem/fastscape):

- drainage area (currently in `StreamPowerLaw`)
- closed depression resolving (it has already its own ``LocalMinima`` routine, but it would be better to call it in ``FastScape_Execute_Step`` instead of inside ``FlowRouting`` and ``FlowRoutingSingleFlowDirection``, so that the two latter can be used independently, e.g., from ``fastscape`` Python).

**Comment by benbovy** [comment]
@jeanbraun -- Regarding drainage area, this issue has been raised by Igor, who needs values of drainage area for computing the SPL K coefficient.

As a workaround, I can re-implement the computation of drainage area in [fastscape](https://github.com/fastscape-lem/fastscape), but this is not very nice because drainage area will be computed twice at each time step.

**Comment by jeanbraun** [comment]
@benbovy -- I am happy to try to split the drainage area into a separate routine; in the mean time Igor should use the drainage area from the previous time step.

**Comment by benbovy** [comment]
Great thank you

> in the mean time Igor should use the drainage area from the previous time step.

Yes that was my advise too.

Although having separate routines is better, just moving the drainage area loops into ``FlowRouting`` and ``FlowRoutingSingleFlowDirection`` would be ok for now.

**Comment by benbovy** [comment]
In case where slope-adaptive multiple direction flow routing is used (i.e., `p = 0.5 + 0.6*slope`), it would be nice to be able recording `p` as model diagnostics, which is not currently possible.
But we can save that for later!

On a side note, I've noticed that the mean of the slopes to the flow receivers is used for ``slope`` in the expression above: 

https://github.com/fastscape-lem/fastscapelib-fortran/blob/fd39d3ff281deaf930cad2887f23da9bf1b0991c/src/FlowRouting.f90#L213

I'm wondering which of the mean, the maximum or the local slope gradient would be the most relevant...

From the high-level perspective (i.e, from [fastscape](https://github.com/fastscape-lem/fastscape)), for more flexibility, I think it would be nice if we could provide user-defined `p` values either as scalar or defined on the grid.

**Comment by benbovy** [comment]
Closed in #25.
