### ISSUE TITLE
Bug in flexure with boundary conditions

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib-fortran#27]
@jeanbraun I suspect there is a bug in `flexure2D.f90` with the boundary conditions (`ibc`).

The example `flexure_test` runs fine:

<img width="550" alt="Screenshot 2019-10-11 at 16 22 47" src="https://user-images.githubusercontent.com/4160723/66659411-bed36600-ec43-11e9-822a-4b5f0ecef43d.png">

But when I flip the settings (i.e., setting `ibc=0010` and flipping also initial elevation and uplift rates), this is what I get:

<img width="560" alt="Screenshot 2019-10-11 at 16 20 48" src="https://user-images.githubusercontent.com/4160723/66659535-f6daa900-ec43-11e9-93a9-27126ab9ac60.png">

The latter doesn't look cyclic on left and right. Erosion is still consistent so I think there might be something wrong in flexure rather than in the model setup.

**Comment by jeanbraun** [comment]
hi @benbovy, I am working on this issue; I found the source of the bug and am trying to fix it. It has to do with integer division that shifts where the BC is imposed.

**Comment by jeanbraun** [comment]
Problem fixed by redesigning the interpolation scheme between load and deflection in the flexure code.
