### ISSUE TITLE
Unable to install your repository.

### ISSUE THREAD

**Issue by v-vladyslav** [fastscape-lem/fastscapelib-fortran#52]
Hello, I've been trying various methods to install your repository (library), but I am encountering an error:

ERROR: Could not find a version that satisfies the requirement fastscapelib_fortran (from versions: none)
ERROR: No matching distribution found for fastscapelib_fortran

I have tried installing through pip, downloading the repository and then installing it, and also through building fastscape.

My system details are:
pip 23.0.1
python 3.7.7
Windows 10 22H2 19045.2604

I am not sure if this information is helpful, but I am hoping you can assist me in resolving this issue.

**Comment by benbovy** [comment]
I'm missing some information like the commands you have been running, but it seems that you're trying to install this library using pip (non-local installation, i.e., not from source). There's no pre-compiled package for this library on pypi.org.

If you want to use it from Python, I strongly recommend you to install fastscape using conda. More info here: https://fastscape.readthedocs.io/en/latest/install.html.

**Comment by benbovy** [comment]
I'm closing this issue since it should be solved with instructions in my last comment. Feel free to re-open it if the issue persists.
