### ISSUE TITLE
Split StreamPowerLaw into several, smaller routines

### ISSUE THREAD

**Issue by benbovy** [fastscape-lem/fastscapelib-fortran#9]
Currently the ``StreamPowerLaw()`` routine does many things, actually much more than solving the SPL (i.e., flow routing, closed depression resolving and even applying uplift). This causes various issues:

- hard to read (for example, it took me some time to figure out that uplift is applied inside this routine)
- some potential performance issues (e.g., flow receivers are re-computed in the ``compute_fluxes`` routine -- could we avoid that?)
- I have to do hacky things to wrap it with xarray-simlab and make it more modular (see https://github.com/fastscape-lem/fastscape/pull/1)

It would be nice if we could split it into smaller pieces with a clearer scope. In order to still constrain the workflow on the public API, we should also update the ``FastScape_Execute_Step`` routine.

cc @jeanbraun

**Comment by jeanbraun** [comment]
I realise this is important. I would like also to be able to return to "simpler" calculation of the stack and other operations using a single receiver. Mostly for performance issues. I am happy to do this in a near future, but could you provide me with a rough idea of the best way to split operations? in this way I can be most efficient, I think.

cc @benbovy

**Comment by benbovy** [comment]
Avoiding too much refactoring, I'd see something like this:

1. declare flow receivers, donors, stack, etc. arrays in ``FastScapeContext``, and allocate/deallocate them in ``SetUp`` and ``Destroy``.

2. extract all code for flow routing in its own source file, e.g., ``RouteFlow.f90`` with a new top-level routine that re-use ``FastScapeContext``. 

3. as applying uplift is straightforward, we could just move the few lines of code from ``StreamPowerLaw`` into a new routine in ``FastScape_ctx.f90``.

4. update ``FastScape_Execute_Step`` with calls to the two new routines created in 2 and 3.  

5. maybe we could avoid re-route flow in ``compute_fluxes`` and instead re-use the arrays in the context?

To speed-up the computation in the case of single flow receivers, an option could be to write a routine ``set_single_rec``, which, called instead of ``find_mult_rec``, would simply assign ``rec(ij)`` to ``mrec(1, ij)`` and set ``mrec``, ``mwrec``, etc. with uniform values. This doesn't optimize memory, but I don't think that's a big concern.  We probably need to extract the local minima filling from ``find_mult_rec``.

**Comment by benbovy** [comment]
Closed in #23
